### ISSUE TITLE
Idea: Import strategies from other packages if they exists

### ISSUE THREAD

**Issue by sergiodxa** [TheRealFlyingCoder/remix-auth-socials#3]
A few of the strategies here are already in other packages. I think if someone already created the individual package of some of them it would be useful to re-export them from remix-auth-socials so you don't need to maintain a copy of the strategy, and while most strategies are probably not going to change a lot if a bug was found in one of them it can be fixed in a single place.

Some strategies already published independently:
- https://github.com/sergiodxa/remix-auth-github
- https://github.com/JonnyBnator/remix-auth-discord
- https://github.com/pbteja1998/remix-auth-google
- https://github.com/juhanakristian/remix-auth-microsoft

There's also https://github.com/chadelofson/remix-auth-facebook but it's not implemented yet.

**Comment by TheRealFlyingCoder** [comment]
So i'm not rushing to do this because of a few things:

1. Trusting that the maintainers will actually fix problems, right now it's whoever was first got it, and we don't know how uptake will go
2. The quality is different between packages, eg:
  `remix-auth-google` has no tests
  `remix-auth-discord` is the only one that exports the scope options type
  
 Right now I can at least provide a consistent experience in one spot, and if all the other packages remain stable and eventually follow the same pattern I can re-export
